apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: egw-client
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: egw-client
      app.kubernetes.io/egw-client-is-bootstrap: "false"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - port: prometheus
    interval: 1s