apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egw-scale-test-route-external
spec:
  selectors:
  - podSelector:
      matchLabels:
        app.kubernetes.io/name: egw-client
  destinationCIDRs:
  - "${EXTERNAL_TARGET_CIDR}"
  egressGateway:
    nodeSelector:
      matchLabels:
        scale.cilium.io/component: egw-node
